#Q1

In [22]:
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [23]:
data=pd.read_csv("/content/Cutlets.csv") # Uploading A Dataset of Cytlets
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [24]:
p_value=stats.ttest_ind(data.iloc[:,0],data.iloc[:,1]) 
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [25]:
# accept null hypothesis as p value is more than alpha 0.05

#question 2

In [26]:
data1=pd.read_csv("/content/LabTAT.csv")
data1.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [27]:
p_value=stats.f_oneway(data1.iloc[:,0],data1.iloc[:,1],data1.iloc[:,2],data1.iloc[:,3])
p_value


F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [28]:
# value of p value i.e. 2.11*10^-57  which is less than alpha 0.05 Reject Null Hypothesis

#Q3

In [29]:
data2=pd.read_csv("/content/BuyerRatio.csv")
data2.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [30]:
X=pd.Series(data2.iloc[0,1:]).values
X

array([50, 142, 131, 70], dtype=object)

In [31]:
Y=pd.Series(data2.iloc[1,1:]).values
Y

array([435, 1523, 1356, 750], dtype=object)

In [32]:
z=[X,Y]
z

[array([50, 142, 131, 70], dtype=object),
 array([435, 1523, 1356, 750], dtype=object)]

In [33]:
from scipy.stats import chi2_contingency                #Chisquare
x=chi2_contingency(z)

In [34]:
x[1]

0.6603094907091882

In [35]:
#p value is greater than Alpha value 0.05 therefore we will Accept Null Hypothesis


# Q4


In [36]:
data3=pd.read_csv("/content/Costomer+OrderForm.csv")
data3.head()


Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [37]:
data3.Phillippines.value_counts()        #Philippines Value Counts

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [38]:
data3.Indonesia.value_counts()          #Indonesia  Value Counts

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [39]:
data3.Malta.value_counts()             # Malta Value Counts


Error Free    269
Defective      31
Name: Malta, dtype: int64

In [40]:
data3.India.value_counts()         # India value Counts

Error Free    280
Defective      20
Name: India, dtype: int64

In [41]:
array = [[271,267,269,280],[29,33,31,20]]    #Joinig The 2 list in array

In [42]:
array

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [43]:
x=chi2_contingency(array)            # Calculating Chi Square

In [44]:
x[1]


0.2771020991233135